-- Room-level detail. property_rooms holds one row per physical room;
-- beds holds one row per bed within a room (a room can have 2 bunk beds,
-- etc.); sleeping_arrangements is a deliberately denormalized per-property
-- summary (see comment below) so the guest-facing "sleeps 8 across 4
-- bedrooms" line never needs a live join across rooms->beds on every page
-- view.

create table public.property_rooms (
  id           uuid primary key default gen_random_uuid(),
  property_id  uuid not null references public.properties(id) on delete cascade,
  room_type_id uuid not null references public.room_types(id),
  name         text not null,          -- "Master Bedroom", "Bedroom 2"
  floor        text,
  area_sqft    integer,
  has_attached_bathroom boolean not null default false,
  has_balcony  boolean not null default false,
  has_ac       boolean not null default false,
  has_wardrobe boolean not null default false,
  has_tv       boolean not null default false,
  has_workspace boolean not null default false,
  description  text,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid references auth.users(id),
  updated_by   uuid references auth.users(id),
  deleted_at   timestamptz
);

create table public.beds (
  id         uuid primary key default gen_random_uuid(),
  room_id    uuid not null references public.property_rooms(id) on delete cascade,
  bed_type   text not null check (bed_type in (
               'king', 'queen', 'double', 'single', 'bunk', 'sofa_bed',
               'floor_mattress', 'crib', 'extra_bed'
             )),
  quantity   integer not null default 1,
  capacity_per_bed integer not null default 2, -- crib/single=1, king/queen/double=2, bunk=2 (one per level)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  deleted_at timestamptz
);

-- Denormalized on purpose: max_guests/bedroom_count already live directly on
-- `properties` (added in 20260731000001); this table holds the *bed-type
-- breakdown* specifically (e.g. "2 king, 1 bunk"), regenerated by the
-- trigger below whenever `beds` changes, so the summary is never stale and
-- never requires a live join to render.
create table public.property_sleeping_arrangements (
  property_id  uuid primary key references public.properties(id) on delete cascade,
  bed_summary  jsonb not null default '[]'::jsonb, -- [{type:"king",count:2},{type:"bunk",count:1}]
  updated_at   timestamptz not null default now()
);

create index property_rooms_property_idx on public.property_rooms (property_id) where deleted_at is null;
create index beds_room_idx on public.beds (room_id) where deleted_at is null;

create trigger set_updated_at before update on public.property_rooms
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.beds
  for each row execute function public.set_updated_at();
create trigger set_audit_columns before insert or update on public.property_rooms
  for each row execute function public.set_audit_columns();
create trigger set_audit_columns before insert or update on public.beds
  for each row execute function public.set_audit_columns();

create or replace function public.refresh_sleeping_arrangement()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  target_property_id uuid;
begin
  select r.property_id into target_property_id
  from public.property_rooms r
  where r.id = coalesce(new.room_id, old.room_id);

  insert into public.property_sleeping_arrangements (property_id, bed_summary, updated_at)
  select
    target_property_id,
    coalesce(jsonb_agg(jsonb_build_object('type', b.bed_type, 'count', b.quantity)), '[]'::jsonb),
    now()
  from public.beds b
  join public.property_rooms r on r.id = b.room_id
  where r.property_id = target_property_id and b.deleted_at is null
  on conflict (property_id) do update
    set bed_summary = excluded.bed_summary, updated_at = now();

  return coalesce(new, old);
end;
$$;

create trigger refresh_sleeping_arrangement
  after insert or update or delete on public.beds
  for each row execute function public.refresh_sleeping_arrangement();
