import { chromium } from "playwright";
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const token = process.argv[3];
await context.addCookies([{ name: "everloft_session", value: token, domain: "localhost", path: "/" }]);
const page = await context.newPage();
await page.goto(`http://localhost:3000${process.argv[4]}`, { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: process.argv[2], fullPage: true });
await browser.close();
